const forbiddenWords = [
"syksymmäksi", "paskapää", "abortoida", "abortointi", "abortti", "aborttipilleri", "aborttitabletti", "ahdinko", "ahdinkotila", "ahdistaja", "ahdistelija", "ahdistella", "ahdistelu", "aiheetottomasti", "ahdistuneisuushäiriö", "ahdistusneuroosi", "ahdistustila", "ahmimishäiriö", "ahteri", "AIDS", "AIDS-potilas", "aikamiina", "aikapommi", "aistiharha", "aistivammainen", "aitosyöpä", "aivohalvaus", "aivoinvalidi", "aivojenpesu", "aivokalvontulehdus", "aivokasvain", "aivokuolema", "aivokuollut", "aivokuume", "aivoleikkaus", "aivosairaus", "aivovamma", "aivovammainen", "aivovaurio", "aivovauriolapsi", "aivoverenvuoto", "aivoveritulppa", "ajetuksissa", "ajatusharha", "ajomiina", "akkamainen", "akkamaisuus", "akkavalta", "akseptata", "akseptaus", "aktiivat", "alakynteen", "alapää", "alastonkuva", "alastonmalli", "aliravittu", "alkeistiedot", "alkoholihumala", "alkoholimyrkytys", "alkoholiongelma", "alkoholiongelmainen", "alkoholiriippuvuus", "alkoholismi", "alkoholisoitua", "alkoholisti", "alkuopinnot", "amfetamiini", "ammattihaureus", "ammattitappaja", "ammis", "amokjuoksija", "amokjuoksu", "analfabeetti", "anamnestinen", "antidepressiivi", "antikristus", "antisemiitti", "antisemiittinen", "antisemiittisesti", "antisemitismi", "antisosiaalinen", "apartheid", "apartheidpolitiikka", "apukoulu", "arjalainen", "armomurha", "arvostelukyvyttömästi", "asbestikangas", "asbestikuitu", "asbestilevy", "asbestoosi", "asosiaalisesti", "askele", "aspi", "asuin-", "asuma", "asutustilallinen", "atk-kirjoittaja", "atk-pohjainen", "atropia", "atto-", "aussi", "avionrikkoja", "aviorikos"
,"banaanivaltio", "bandiitti", "barbaari", "barbaarimainen", "barbaarimaisesti", "barbaarimaisuus", "barbaarinen", "barbaarisesti", "barbaarisuus", "bastardi", "besserwisser", "bioase", "biataisteluaine", "bolsevikki", "bolsevikkivallankumous", "bolševikkivallankumous", "blondiini", "brenkku", "broileripoliitikko", "bryssä", "buliimikko", "bulimia", "burnout", "busmanni", "bušmanni", "bänet", "bänks", "crack", "debiili", "deekikselle", "deekiksellä", "deeku", "delata", "dementikko", "dementti", "depis", "depressiivinen", "depressiivisesti", "depressiivisyys", "depressio", "depressiokausi", "depressiolääke", "depressiotila", "desantti", "diabeetikko", "diabetes", "diatsepaami", "diileri", "diivailla", "diivailu", "diivata", "diletantti", "dokata", "dokaus", "doku", "dorka", "dorkasti", "doupata", "dumdumluoti", "dödö", "dösä"
,"edelle", "edellä esitetty", "edellä mainittu", "edeltä", "edeltäkäsin", "edeltäpäin", "edemmä", "edemmäksi", "edemmäs", "edempänä", "edempää", "edespäin", "edessäpäin", "edestä", "edestäpäin", "editse", "edusteilla", "eespäin", "ehdyksiin", "ehdyksissä", "ei-kenenkään-maa", "ejakulaatio", "ekshibitionismi", "ekshibitionisti", "ekshibitionistinen", "ekstaasi", "eksyksiin", "eksyksissä", "eksyksistä", "elinkautistuomio", "elinkautisvanki", "elintasopakolainen", "elohopeamyrkytys", "eloon", "elostelija", "elostella", "elostelu", "elukka", "elähtänyt", "eläinkoe", "eläinrääkkäys", "elämänkielteinen", "elämänkielteisesti", "elämänkielteisyys", "elämänpelko", "elätti", "elättivaris", "elävältä", "emakko", "emätin", "emätinhuuhtelu", "emätinpuikko", "emätintulehdus", "emävalhe", "engelsmanni", "ennakkoon", "ennakolta", "ennallaan", "ennalleen", "ennalta", "ennemmin", "ennestään", "ennustajaeukko", "ensiksi", "ensimmältä", "ensinkään", "ensinnä", "entiselleen", "entisellään", "entisensä", "entisestään", "epeli", "epileptikko", "e-pilleri", "epähuomiossa", "epäkunnossa", "epäkuntoon", "epäkäs", "epäsikiö", "epätoivoissaan", "epävireeseen", "epävireessä", "erektio", "erilleen", "eroon", "eroottisesti", "eroottistaa", "eroottistua", "erotisoida", "erotisointi", "erotisoitua", "erotomaani", "erotomania", "esiaviollinen", "esileikki", "esinahka", "esipuberteetti", "eskimo", "eskimokajakki", "eskimokoira", "eskimopyörähdys", "eturauhanen", "etäpesäke", "eunukki", "eutanasia", "evakko"
, "fakki-idiootti", "fallinen", "fallos", "fallossymboli", "fasismi", "fasisti", "fasistinen", "fasistipuolue", "femakko", "fetisismi", "fetisisti", "fetisistinen", "fetissi", "fissiopommi", "frigidi", "frigiditeetti", "frigidiys", "friikki", "fritsu", "fudut", "fuusiopommi"
, "gangsteriliiga", "gangsterismi", "gay", "genitaalinen", "genitaalit", "getto", "gettoistua", "gettoutua", "ghetto", "ghettoutua", "gigolo", "giljotiini", "gonokokki", "gonorrea", "granaatti", "gravidi", "graviditeetti", "gynekologi", "gynekologia", "gynekologinen", "gängi" 
, "haaksirikkoinen"
, "haamuasiakas", "haamupotilas", "haaremi", "haaskautua", "haastaja", "haastehakemus", "haastemies", "haavainen", "haavakko", "haavakuume", "haavamuodostuma", "haavatartunta", "haavatulehdus", "haavautua", "haavautuma", "haaveri", "haavoittuva", "hahattaa", "haihattelija", "haimaneste", "haimasyöpä", "haimatulehdus", "hairahdus", "hairahtuvainen", 
"haistatella", "haistattaa", "haistattelu", "haisuliini", "haitallisesti", "haitta-aste", "hajaannustila", 
"hajupommi", "hajuvirhe", "hakaristi", "hakaristilippu", "hakata", "hakkelus", "hakkuukielto", "hakoteille", "hakoteillä", "haksahdus", "haksahtaa", "hakuammunta", "hakusaarto",
, "halikkain", "hallintoalamainen"
, "hallitustenvälinen", "hallussa", "hallusta", "halpa-arvoinen", "halpa-arvoisuus", "halpahintainen", "halpakorkoinen", "halpamaisesti", "haltioihinsa", "haltioissaan", "haltuun", "halukkaasti", "halullinen", 
, "haluttomasti", "halvattu", "halveerata", "halveksinta", "halvennus", "halventavasti", "hamevalta"
, "hampaattomasti", "hampaattomuus", "hamppari", "hampparoida", "hampuusi", "hanakasti", "handicap", "handu", "hangoitella", "hankalakulkuinen", "hankalatöinen"
, "hanslankari", "hantlankari", "hanttapuli", "hantti", "hanttiin", "hanttikortti", "hanttimies", "hanttityö", "happamesti", "happoveikko", "happy hour"
, "harakanvarvas", "harakiri", "haralla", "haralle", "haralleen", "harhaan", "harhaannuttaa", "harhaantua", "harhaanvievä", "harhahavainto", "harhaheitto", "harhainen", "harhaisku", "harhakuva", "harhakäsitys", "harhalaukaus", "harhaluoti", "harhamielisyys", "harhanäky", "harhasoitto", "harhassa", "harhasyöttö", "harhateille", "harhateillä", "harhateiltä", "harhauma", "harhautuma", "harilla", "harillaan", "harille", "harilleen", "harjaantumiskoulu"
, "harkitsevuus", "harkittu", "harmaahapsinen", "harmaapartainen", "harmaatukkainen"
, "harmissaan", "harmistuksissaan"
,"harvainvalta", "harvainvaltainen", "harvalukuinen", "harvasanainen", "harvassa", "harvempaan", "harventamaton", "hasardi", "hasis", "hassahtanut", "hassahtava", "hassata", "hassuttaa", "hassutus", "hattureuhka", "hatunreuhka", "hatuttaa", "haudanhiljainen", "haudanhiljaisuus", "haudanhäpäisy", "haudankaivaja", "haudanryöstö", "haudantakainen", "haudanvakavuus"
, "haukkumakirje", "haukkumanimi", "haureellinen", "haureellisuus"
, "hedelmöidä", "hedelmöittyä", "hedelmöittää", "hedelmöityä"
, "heijari", "heikkolahjainen", "heikkolahjaisuus", "heikkomielinen", "heikkomielisyys", "heikkopäinen", "heilaus"
, "heinähattu", "heitteille", "heitteillä", "heitteiltä", "heittopussi"
, "helibor", "heliborkorko", "helkatti", "helkkarinmoinen", "helkkaristi", "helkkari", "helkutti", "hellapoliisi"
, "hellitä", "helppoheikki"
, "helskutti", "helvetillinen", "helvetinkone", "helvetinmoinen", "helvetisti", "helvetti", "hemmetinmoinen", "hemmetisti", "hemmetti", "hempukka", "hengissä"
, "henkihieveriin", "henkihieverissä", "henkiin", "henkilöidä"
, "henkipatto", "henkiriepu", "henkitoreihin", "henkitoreihinsa", "henkitoreisiin", "henkitoreisiinsa", "henkitoreissa", "henkitoreissaan", "hepsankeikka", "hepuli", "hereille", "hereillä"
, "herja", "herjaaja", "herjakirjoitus", "herjasana", "herjata", "herjaus", "herkkyys", "herkkä", "herkkähipiäinen", "herkkänahkaisuus", "hermoheikko", "hermoraunio", "hermostuksissaan"
, "heroiini", "heroinisti", "herrajesta", "herrajestas", "herrakansa", "herranen", "herranjesta", "herranjestas", "herranterttu", "herraviha", "herraus"
, "herättää", "herätä", "hetkahtaa", "hetkauttaa", "hetkua", "hetkutella", "hetkuttaa", "hetkutus", "hevostella"
, "hidastaa", "hidastella", "hidastua", "hidastuttaa", "hiekka-aavikko", "hiekkapestä", "hiekkapuhaltaa", "hiekoittaa", "hienohelma"
, "hienontaa", "hienontua", "hienosahata", "hienostella", "hienostua", "hienosäätää", "hienota", "hieraista", "hieroa", "hieromasauva", "hieroskella", "hierottaa", "hieroutua", "hiertyä", "hiertää", "hiestyä", "hiestää", "hievahtaa", "hievauttaa", "hiffata", "hihhuli", "hihhuloida", "hihitellä", "hihittää"
, "hihkaista", "hihkua", "hihnoittaa", "hiihdellä", "hiihtää", "hiilettyä", "hiilettää"
, "hiillostaa", "hiillostua", "hiillyttää", "hiiltyä", "hiiltää", "hiipata", "hiipiä", "hiippailla", "hiippari", "hiipua", "hiiskahtaa", "hiiskua", "hiitata", "hiivata", "hiivatinmoinen", "hiivatisti", "hiivatti", "hiiviskellä", "hikeentyä", "hikeytyä", "hikipinko", "hikipäissä", "hikipäissään", "hikoilla", "hikoiluttaa", "hilata", "hilautua", "hilavitkutin", "hiljakkoin", "hiljakseen", "hiljalleen", "hiljan"
, "hiljentyä", "hiljentää", "hiljetä", "hilkulla", "hilleri", "hillitä", "hillota", "hilloutua", "hillua", "hilpaista", "hilsehtiä", "hilseillä", "hilsettyä", "himmennyttää", "himmentyä", "himmentää", "himmetä", "himoita", "himomurha", "himomurhaaja", "himota", "himottaa", "himpun", "hinata", "hinauttaa", "hinautua", "hinkata", "hinkki", "hinkua", "hinnoitella"
, "hinnoittaa", "hinttari", "hintti", "hinttiys", "hioa", "hiostaa", "hiostua", "hiostuttaa", "hiota", "hiottaa", "hioutua", "hipaista", "hipat", "hipelöidä", "hipoa", "hippasilla", "hippasille", "hippulat", "hiprakka", "hipsiä", "hipsutella", "hipsuttaa"
, "hirmustua", "hirmuteko", "hirmutyö", "hirmuvalta", "hirnahdella", "hirnahtaa", "hirnua", "hirsipuu", "hirttyä", "hirttäytyä", "hirttää", "hirtättää", "hirvestää", "hirvetä", "hirvitellä", "hirvittää", "hirvitä", "hisahtaa", "hissata"
, "hissukka", "hissukseen", "hissuksiin", "hissun kissun", "hissutella", "hissuttaa", "historioida", "hitonmoinen", "hitosti", "hitsaantua", "hitsata", "hitsautua", "hitto", "hittolainen", "hiuduttaa", "hiukaista", "hiukoa", "hiuksenhalkominen"
, "hiustenhalkaisu", "hiustenhalkoja", "hiustenhalkominen", "hiutua", "hivauttaa", "hivellä", "hiveltää", "hivuttaa", "hivuttautua", "hohdella", "hohhoijaa", "hohkata", "hohkua", "hohoi", "hohottaa", "hohtaa", "hoidattaa", "hoidella", "hoikentaa", "hoikentua"
, "hoitajatar", "holhokki", "holhotti"
, "holokausti", "holtittomasti", "homekorva", "homo", "homoeroottinen", "homofiili", "homofiilinen", "homofiilisuus", "homofiilius", "homofobia", "homoliitto", "homopari", "homoseksuaali", "homoseksuaalinen", "homoseksuaalisuus", "homoseksualismi", "homoseksualisti", "homous"
, "horisko", "horkka", "horna", "hornankattila", "horre"
, "horteessa", "hoteisiin", "hoteissa", "hoteista", "hotellipoika", "hottentotti", "houkka", "houkkamainen", "houkkio", "hourula", "hourupäinen", "housusillaan", "housusilleen"
, "huikeasti", "huikentelevaisesti", "huikentelevasti", "huimapäisesti", "huimasti"
, "huithapeli", "huitukka", "hujakoilla", "hujan hajan", "hujoppi", "hukassa", "hukkaan", "hukkateille", "hukkateillä", "hukuksiin", "hukuksissa", "huligaani", "hulivilipoika", "hulivilityttö", "hullujenhuone"
, "hullunkurisesti", "hullusti", "hulttio", "hulttiomainen", "humalapäissä", "humalapäissään", "humoristisesti", "humpuuki", "hunajaisesti", "hunajapupu", "hunni"
, "hunningolla", "hunningolle", "hunsvotti", "huolehtivaisesti", "huolellisesti", "huoleti", "huoletta", "huolettomasti", "huolimatta", "huolimattomasti", "huolissaan"
, "huomaamattomasti", "huomaan", "huomaavaisesti", "huomassa", "huomattavasti", "huomenissa", "huomenna", "huomionkipeä", "huomioon ottaen", "huonomaineinen", "huono-oppinen"
, "huonosti", "huonotapainen", "huora", "huorahtava", "huorata", "huorin", "huorintekijä", "huorinteko", "huoripukki", "huoruus", "huostaan", "huostassa", "huostasta", "huovikas", "hupaisasti", "hupakko", "hupiveikko", "huppeli", "hupsia", "hupsis", "hupsista", "hupsusti", "hurjasti"
, "hurme", "hurmeinen", "hurmosliike", "hurri", "huru-ukko", "hutsu", "hutu"
,"huumausaine", "huume", "huumejengi", "huumekasvi", "huumekauppa", "huumekauppias", "huumeklinikka", "huumekoira", "huumekuriiri", "huumenuori", "huumepoliisi", "huumepotilas", "huumeriippuvuus", "huumerikollisuus", "huumerikos", "huumetesti", "huuri", "huusi", "huussi", "huut", "huuti", "huutolainen", "huutolaispoika",
, "huvitutti", "hyeena", "hyh", "hyi", "hylkiö", "hylkyauto", "hymen"
, "hynä", "hyperventilaatio", "hypnoosi", "hypnotisoida", "hypotermia", "hys", "hysteerikko", "hysteerinen"
,"hysteria", "hyväksikäyttö", "hyväkäs"
, "hyypiö", "hyysätä", "hyödyksikäyttö", "hyödykäs", "hyökkäys", "hyökkäysase", "hyökkäyssota", "hyökkäysuhka", "hyökkäysvaunu", "hyökkääjä", "hyökkäävä", "hyökkäävästi", "hyökätä", "hyönteismyrkky"
, "hyötöreaktori", "hä", "hädissään", "hädänalainen", "häh", "hähättää", "häijy", "häijynilkinen", "häijysti", "häijyys", "häikkä", "häikäilemättä", "häikäilemättömyys", "häikäilemättömästi", "häikäilemätön", "häippäistä", "häiriintynyt", "häiriintyä", "häirikkö", "häiriköidä", "häirintä", "häirintätuli", "häiritsijä", "häiritä", "häiriö", "häiriötila", "häiskä", "häjy", "häkäkaasu", "häkämyrkytys"
, "hämärämies", "hämäräperäinen", "hännystelijä", "hännystellä", "hännystely", "häntyri", "häpeissään", "häpeä", "häpeällinen", "häpeällisesti", "häpeämerkki", "häpeämättömyys", "häpeämättömästi", "häpeämätön", "häpeäpaalu", "häpeäpenkki", "häpeäpilkku", "häpeärangaistus", "häpeätahra"
, "häppä", "häpy", "häpyhuuli", "häpykannus", "häpykarvat", "häpykarvoitus", "häpykieli", "häpykukkula", "häpyluu", "häpäistä", "häpäisy", "härkäpäinen", "härski", "hässiä", "hässäkkä", "hätähousu", "hätäinen"
, "hätäpäissään", "hätäteurastaa", "hätäteurastus", "hätätila", "hätävalhe", "hätäännyksissä", "hätäännyksissään", "hätäännys", "hävittäjä", "hävittäjäalus", "hävittäjäkone", "hävittäjälaivue", "hävittäjälentokone", "hävittäjälentäjä", "hävittäjäpommittaja", "hävittää", "hävitys", "hävyttömyys", "hävyttömästi", "hävytön", "häväistys", "häväistysjuttu", "häväistyskirjoitus", "häväistä", "häätää", "häätö", "häätömääräys"
, "häävuode", "höhlä", "hökkeli", "hökkelikaupunki", "hökkelikylä", "hökötys", "hölinä", "hölmö", "hölmöläinen", "hölynpöly", "hölö", "hölösuinen", "hölösuu", "hömppä", "hömppäsivu", "hömpsy", "hömpsötys", "hömpötys", "höntti", "hönö", "höperö", "höpinä", "höppänä", "höpsähtänyt", "höpsähtävä", "höpsö", "höpö", "höpöpuhe", "höpötys", "hörhelö", "hörhö", "hörppy", "hörtsö", "hörähdys", "hörökorva", "hörönauru",
, "höröttää", "hörötys", "höskä", "hösseli", "hössäkkä", "hössötys", "hötkyily", "höttö", "höttösissään", "hötäkkä", "hötö", "höyde", "höyhensaaret", "höykky", "höykänen", "höynä", "höyrypäinen", "höyrypää"
, "höyrähtää", "höösätä", "höösäys", "icing", "identiteettikriisi", "idiootti", "idioottimainen", "idioottimaisuus", "idioottivarma", "idis", "idoli", "ientulehdus",
, "ihmiskilpi", "ihmismetsästys",
"ihmispeto", "ihmisraunio", "ihmisryöstö", "ihmissyöjä", "ihmissyönti", "ihmistäi", "ihmisuhri", "ihmisviha", "ihmisvihaaja", "ihmokasvain", "ihomato", "ihosyöpä", "ihra", "ihramaha", "ihramahainen", "iilimato", "iiri", "iiriläinen", "iirin kieli", "iiris", "iirishimmennin", "iirispainanta", "iirispainatus", "iivana",
"ikenet", "iki-ihastunut", "ihanne-", "ihme-", "ikäkausikilpailut", "ikäkulu"
,"ikäloppu", "ikäneito", "ikäsyrjintä", "ikävissään", "ikävystynyt", "iljettävyys", "iljettävä", "iljettää", "iljetys", "ilkeillä", "ilkeily", "ilkeys", "ilkeä", "ilkeäluonteinen", "ilkeämielinen", "ilkeämielisyys", "ilkeännäköinen", "ilkialasti", "ilkialaston", "ilkikurinen", "ilkimys", "ilkityö", "ilkivalta", "ilkivaltainen", "ilkivaltaisuus", "ilkiö", "ilkkua", "ilkosillaan", "ilkosilleen"
, "ilma-ase", "ilmaherruus", "ilmahyökkäys", "ilmahälytys", "ilmais-", "ilmaisku", "ilmajuoppo", "ilmakivääri", "ilmakuoppa",
, "ilmansaaste", "ilmapistooli", "ilmapistooliammunta", "ilmarinta", "ilmarosvo", "ilmarosvous", "ilmasodankäynti", "ilmasota", "ilmataistelu", "ilmatorjunta", "ilmatorjunta-ase", "ilmatorjuntajoukot", "ilmatorjuntaohjus", "ilmatorjuntapatteri", "ilmatorjuntapatteristo", "ilmatorjuntatuli", "ilmatorjuntatykistö", "ilmatorjuntatykki", "ilmavaara", "ilmavaivat"
, "ilmavoimat", "ilmavoitto", "ilmeettömästi", "ilmeillä", "ilmeily", "ilmiantaa", "ilmiantaja", "ilmianto", "ilmiantovelvollisuus", "ilmielävästi", "ilmiriita", "ilmiselvästi", "ilmisota", "ilmiömäisesti", "ilmoitse", "iloisesti", "iloissaan", "ilokaasu", "iloliemi", "ilolintu", "ilonpilaaja"
, "ilotalo", "ilottomasti", "ilotyttö", "iltaisin", "iltasella"
, "imbesilli", "imelästi", "immenkalvo", "immuunistaa", "immuunistua", "impata", "implisiittisesti", "impotenssi", "impotentti", "imppaus"
, "impulsiivisesti", "individualistisesti", "indusoida", "indusoitua"
, "informaatiosota", "inhimillisesti", "inhottavasti", "inkkari", "inkontinenssi", "innoissaan", "innokkaasti", "innostuksissaan", "innostuneesti"
, "innottomasti", "insesti", "intensiivisesti", "interaktiivisesti", "intertekstuaalisesti"
, "intiimisti", "intohimoisesti", "intohimottomasti", "intomielisesti", "intrigoida", "intrigointi", "inttää", "intuitiivisesti", "invalidi", "invalidisoida", "invalidisoitua", "invalidoida", "invalidoitua", "irkata"
, "ironisesti", "irrallaan", "irralleen", "irrallisesti", "irrationaalisesti", "irstaasti", "irstailija", "irstailla", "irstailu", "irstainen", "irstas", "irstaus", "irti", "irtolainen", "irtonaisesti", "irveen", "irvessä", "irviin"
, "irvissä", "irvokkaasti", "iskevästi", "isi", "iskä"
, "isomahainen", "isosti", "isosuinen", "istualla", "istuallaan", "istualle", "istualleen", "istualta", "istualtaan", "istumalla", "istumalta"
, "istuvilla", "istuvillaan", "istuville", "istuvilleen", "istuvilta", "istuviltaan", "isukki", "isällisesti", "isänmaallisesti", "isäpappa", "isäukko", "italiaano", "itarasti", "itkeskellä", "itkusilmin", "itsari"
, "itsehalveksinta", "itsehalveksunta", "itseihailu", "itseinho", "itseiva", "itsekehu", "itsekeskeinen", "itsekeskeisyys", "itsekidutus", "itsekkyys", "itsekäs", "itsemurha", "itsemurhaaja", "itsemurhaisku", "itsemurhakandidaatti", "itsemurhalentäjä", "itsemurhaterrorismi", "itsemurhaterroristi", "itsemurhayritys", "itsensäpaljastaja", "itsensäpaljastaminen", "itserakas", "itserakkaus"
, "itseruoskinta", "itsesoimaus", "itsessään", "itsestään", "itsesyytös", "itsesääli", "itsetuho", "itsetuhoinen", "itsetuhokäyttäytyminen", "itsetypistys", "itsetyydytys"
, "iva", "ivahymy", "ivailla", "ivailu", "ivallinen", "ivamukaelma", "ivanauru", "ivata", "iätä"
, "jakomielinen", "jakomielisyys", "jakomielitauti", "jalan", "jalkahiki", "jalkainvalidi", "jalkapuoli", "jalkapuu", "jalkarätti", "jalkasieni", "jalkasilsa"
, "jalkavaimo", "jalkavaivainen", "jalkoväli", "jallittaa", "jallitus", "jamaan", "jamassa"
, "jannu", "japsi", "jarrutuslakko", "jarrutuspolitiikka"
, "jees-mies", "jeesustella", "jeesustelu", "jeeveli", "jengi", "jengiläinen", "jenginuori", "jenkki", "jenkkilä", "jepari", "jeppe", "jessus", "jesuiittamainen"
, "jobbari", "jobinposti", "johdonmukaistaa", "johtajantauti", "johtotroikka"
, "jokapaikanhöylä", "jolppi", "jonne", "jonninjoutava"
, "jonne", "jorina", "jorista", "joro", "jorottaa", "jorotus", "jorpakko", "jortsut", "joukkio", "joukkohauta", "joukkohautaus", "joukkohysteria", "joukkomurha", "joukkomurhaaja", "joukkopsykoosi"
, "joukkotuho", "joukkotuhoase", "joukkotuhonta", "joukoittain", "jouluinen", "joulukuinen", "joulunpunainen"
, "journalistinen", "jousittaa", "joustaa", "joustamaton", "joustava", "joustavasti", "joustavoida", "joustavoittaa", "joustokankainen", "joutaa", "joutava", "joutavanpäiväinen", "jouten", "joutenolo", "joutessa", "joutessaan", "joutilaisuus", "joutilas", "joutua", "joutuin", "joutuisa", "joutuisasti", "joviaali", "joystick", "judata", "jugendtyylinen"
, "jugoslavialainen", "juhla-asuinen", "juhlaliputettu", "juhlallinen", "juhlallisesti", "juhlamielinen", "juhlapukuinen", "juhlava", "juhlavalaistu", "juhlavasti", "juhlia", "juhlistaa", "juippi", "jujuttaa", "jukeboksi", "jukebox", "jukolaut", "jukolauta", "jukoliste", "jukra", "juksata", "juku", "jukuripäinen", "juliaaninen", "julistaa", "julistaja", "julistautua"
, "juljeta", "julkaisematon", "julkaista", "julkea", "julkeasti", "julkilausua", "julkimo", "julkinen", "julkipanna", "julkipuhunta", "julkishallinnollinen", "julkisoikeudellinen", "julkistaa", "julkituoda", "julkkis", "julkku", "julli", "jullikka", "julma", "julmasti", "julmettu", "julmetusti", "julmistella", "julmistua", "julmuri", "jumalaapelkäävä", "jumalainen", "jumalaisesti", "jumalakeskeinen", "jumalallinen", "jumalankieltäjä", "jumalankieltäminen", "jumalanpilkka", "jumalaton", "jumalattomasti", "jumalaut", "jumalauta", "jumalinen", "jumalisesti", "jumaliste", "jumaloida"
, "jumaluusopillinen", "jumiintua", "jumittaa", "jumittua", "jumiuttaa", "jumiutua", "jumpata", "jumputtaa", "junailla", "junk food", "junkkari", "junnata", "junnu", "juntata", "juntta", "junttapulla", "junttaus", "juntti", "juoda", "juohea", "juoheasti", "juoheus", "juoheva", "juohevasti", "juohevuus", "juohtua", "juoksennella", "juoksettaa", "juoksettua", "juokseva", "juoksevasti", "juoksuhauta", "juoksujalkainen", "juoksupoika", "juoksuttaa", "juolahtaa", "juolua", "juomahimo", "juomakausi", "juomakierre", "juomari", "juomingit", "juomuinen", "juomukondomi", "juonellinen", "juonellisesti", "juonia", "juonikas", "juonikkaasti", "juonitella", "juonittelija", "juontaa", "juonteikas", "juontua", "juoponnapissa", "juoponnappiin", "juopotella", "juoppo", "juoppohullu", "juoppohulluus", "juoppojuna", "juoppolalli", "juopporatti", "juopporenttu", "juopua", "juopunut", "juoruakka", "juoruilla", "juorukello", "juoruta", "juoruämmä", "juosta", "juotava", "juottaa"
, "juottola", "juovainen", "juovikas", "juovittaa", "juovukkeeseen", "juovukkeessa", "juovuksiin", "juovuksissa", "juovuspäissä", "juovuspäissään", "juovuttaa", "jupista", "juppiutua", "juridinen", "juridisesti", "jurnuttaa", "juroa", "jurosti", "jurottaa", "juroutua", "jurppia", "jurrata", "jurri", "jurrikka", "justeerata", "jutaa", "jutella", "jutku", "jutsku", "jutustaa", "jutustella", "jututtaa", "juudas", "juukeli", "juupeli", "juurakkoinen", "juurehtia", "juurekas", "juureton", "juureva", "juurihoitaa", "juuria"
, "juurittaa", "juurrettava", "juurruttaa", "juurtaa", "juurtua", "juustottua", "juustouttaa", "juustoutua", "juutalaisvaino", "juutalaisvastainen", "juutalaisvastaisuus", "juutalaisviha", "juutas", "juuttua", "jydätä", "jyhkeästi", "jykertää", "jykeväleukainen", "jykevästi", "jykevätekoinen", "jylhetä", "jylhistyä", "jylhästi"
, "jylistä", "jyllätä", "jymistä", "jymistää", "jymähdellä", "jymähtää", "jymäytellä", "jymäyttää", "jynssätä", "jyristellä", "jyristä", "jyristää", "jyrisyttää", "jyrkentyä", "jyrkentää", "jyrketä", "jyrkistyä", "jyrkistää", "jyrkkäkaarteinen", "jyrkkäkattoinen", "jyrkkäluonteinen", "jyrkkänousuinen", "jyrkkäotteinen", "jyrkkäpiirteinen", "jyrkkärantainen", "jyrkkärinteinen", "jyrkkäsanainen", "jyrkkäseinäinen", "jyrkkäsävyinen", "jyrkästi", "jyrrätä", "jyrsiä", "jyrytä", "jyryyttää", "jyrähdellä", "jyrähtely", "jyrähtää", "jyrätä", "jyräyttää", "jyskiä", "jyskytellä", "jyskyttää", "jyskyä", "jyskähtää", "jyskää", "jysähdellä", "jysähtää", "jysäyttää", "jytistä", "jytistää", "jytkyttää", "jytkähtää", "jytyyttää", "jytää", "jyvittää"
, "jyväjemmari", "jyystää", "jähmettyä", "jähmettää", "jähmetä", "jähmeästi", "jäitse", "jäkälöityä", "jäkättää", "jäljekkäin", "jäljelle", "jäljellä", "jäljemmä", "jäljemmäksi", "jäljemmäs", "jäljempänä", "jäljempää", "jäljentyä", "jäljentää", "jäljessä", "jäljestä", "jäljestäpäin", "jäljestää", "jäljetysten", "jäljetön", "jäljille", "jäljillä", "jäljiltä", "jäljitellä", "jäljittää", "jälkeen", "jälkeenjääneisyys", "jälkeenjäänyt", "jälkeenpäin", "jälki-ilmoittautua", "jälki-istunta", "jälki-istunto", "jälkikypsyttää", "jälkikypsyä"
, "jälkikäteis-", "jälkkäri"
, "jänishousu", "jänisrutto", "jännitys-"
, "järjestöjyrä", "järjettömyys", "järjetön", "järkky"
, "jästipää", "jätkä", "jätski"
, "jätti-", "jättiläis-", "jätös", "jäykkäniska", "jäykkäniskainen"
, "jääkaappi-pakastin", "jäärä", "jääräpäinen", "jääräpäisyys", "jääräpää"
, "jää-viileäkaappi", "jörrikkä", "jörö", "jöröjukka", "jössikkä", "jötikkä", "jöö", "kaahaaja", "kaahailija", "kaahari", "kaakki"
, "kaappijuoppo", "kaara"
, "kaasukammio", "kaasukuolio", "kaasus", "kaatokänni", "kaatumatauti"
, "kadotus", "kahareisin", "kahden kesken"
, "kahdessadas", "kahdestaan", "kahdesti", "kaheli", "kahjo", "kahju", "kahta", "kahtaalla", "kahtaalle", "kahtaalta", "kahtaanne", "kahtapuolin", "kahtia", "kahvipapu"
, "kai", "kaikaa", "kaiken kaikkiaan", "kaiketi", "kaikin", "kaikista", "kaikitenkin", "kaikkein", "kaikkiaan", "kaikkialla", "kaikkialle", "kaikkialta", "kaikkianne", "kaikusuhteet", "kainalokarvat"
, "kaistapäinen", "kaistapää", "kait", "kaiunta", "kaivu"
, "kajeontelo", "kajetto", "kakara", "kakaramainen", "kakata", "kakattaa", "kakka", "kakkahätä", "kakkainen", "kakkia", "kakkulat", "kakru", "kaks", "kaksari"
, "kaksikymppinen", "kaksimielinen", "kaksimielisyys", "kaksin", "kaksinaamainen", "kaksinaamaisuus", "kaksinaismoraali", "kaksineuvoinen", "kaksineuvoisuus", "kaksinkertaisesti", "kaksistaan", "kaksisukupuolinen", "kaksisukupuolisuus", "kaksittain"
, "kaksois-", "kaksosparikki", "kalahdella", "kalahdus", "kalahtaa"
, "kalanperkeet", "kalansilmäinen", "kalatäi", "kalauttaa", "kaleeriorja", "kaleerivanki"
, "kaliumsyanidi", "kaljabasso", "kaljamaha", "kaljoitella", "kalju", "kaljupäinen", "kaljupää", "kalkkaa", "kalkkis", "kallellaan", "kallelleen"
, "kallonkutistaja", "kalmanhaju", "kalmankalpea", "kalmo", "kalmukki", "kalpaten", "kalpeanaama", "kalppia", "kalsa", "kalsareisillaan", "kalsareisilleen", "kalsarisillaan", "kalsarisilleen", "kalsarit"
, "kalsongit", "kalterit", "kaltoin", "kalu", "kalukukkaro", "kalvia", "kalvin", "kalvinpora", "kalvinta", "kama", "kamala", "kamaluus"
, "kamikazelentäjä", "kammoa", "kammottava", "kammottavasti", "kanalja", "kanamainen", "kanamaisesti", "kanankakka", "kananlanta"
, "kananpää", "kanervakäärme", "kangaskäärme", "kangastaa", "kangastella", "kangastua", "kanittaa",
"kankku", "kankkunen", "kannabis", "kannalla", "kannalle", "kannalta", "kannassa", "kannasta", "kannibaali", "kannibaalinen", "kannibalismi", "kannoilla", "kannoille", "kannoilta"
, "kansalaissota", "kansalliskiihko", "kansalliskiihkoilija", "kansalliskiihkoinen", "kansallismielinen", "kansallismielisyys", "kansallissosialismi", "kansallissosialisti", "kansallissosialistinen"
, "kansankiihottaja", "kansankiihotus", "kansanmurha"
, "kansanvihollinen", "kansanvillitsijä", "kanssa", "kantaan", "kanta-astuja"
, "kantelupukki", "kanttura", "kanttuvei", "kapakka"
, "kapi", "kapiainen", "kapinahenkinen", "kapinaliike", "kapinalippu", "kapinallinen", "kapinallisuus", "kapinamieli", "kapinayritys", "kapinen", "kapinoida", "kapinoija", "kapinointi", "kapinoitsija", "kapitalisti", "kapitalistinen", "kapitulantti", "kappas", "kaput"
, "kardinaalimunaus", "kardinaalivirhe", "karhuaja", "karhuamiskirje"
, "karhukirje", "karhunkoppi", "karhuta", "karjahdella", "karjahdus", "karjahtaa", "karjaista", "karjaisu"
, "karkeakäytöksinen", "karkealuonteinen", "karkeapuheinen", "karkeasanainen", "karkeasti", "karkeistae", "karkeistaos", "karkenee", "karku", "karkuteille", "karkuteillä", "karkuteiltä", "karkuun"
, "karrella", "karrelle", "karsi", "karsinogeeni", "karsinogeeninen", "karsinogeenisuus", "karsinooma"
, "karttupiilo", "karttupiilosilla", "karttusilla", "karussa", "karvanaama", "karvanaamainen"
, "kas", "kasapäissä", "kasari", "kasi"
, "kassapäinen", "kassapää", "kastraatio", "kastraatti", "kastroida", "kastrointi", "kasvannainen"
, "kasvettua", "kasvettuma", "kasvimyrkky"
, "kasvohalvaus", "kasvohäiriö", "kasvukipu", "katala", "katalasti", "kataluus"
, "katarri", "katastrofaalinen", "katastrofiapu", "katastrofielokuva", "katastrofirahasto", "katastrofivalmius", "kateeksi", "kateisiin", "kateissa", "kateissaan", "katkaisuhoito", "katkaisuhoitola", "katkeransävyinen", "katkerasti", "katkero", "katkeroittaa", "katkeroitua", "katki", "katkismus", "katkokävely", "katkonaisesti", "katkonaisuus"
, "katovuosi", "katseenvangitsija", "katsoma", "katteeton", "katteinen", "katti"
, "katulapsi", "katumapäälle", "katumapäällä", "katumuspilleri", "katunainen", "katutappelu", "katutyttö", "katuväkivalta", "kauaksi", "kauas", "kauemma", "kauemmaksi", "kauemmas", "kauemmin", "kauempaa", "kauempana", "kauheasti", "kauheus", "kauhistella", "kauhistua", "kauhistus", "kauhistuttaa", "kauhuissaan", "kauhujuttu", "kauhukakara"
,"kauimma", "kauimmaksi", "kauimmas", "kauimmin", "kauimpaa", "kauimpana", "kauintaan", "kaukaa", "kaukana", "kaukolasit", "kaukonäköisesti", "kaukovalot"
,"kaulakkain", "kaulata", "kaulatuksin", "kaulatusten", "kaulia", "kaulita", "kauniisti", "kaunistaa", "kaunistautua", "kaunistella", "kaunistua", "kaupaksi käymätön", "kaupaksi käyvä", "kaupaksi menevä", "kaupallisesti", "kaupallistaa", "kaupallistua"
,"kaupata", "kaupinta", "kaupita", "kaupitella", "kaupungeittain"
, "kaupungistaa", "kaupungistua", "kaupunkilaisesti", "kaupunkilaisittain", "kaupunkilaistua", "kaupunkimaistaa", "kaupunkimaistua", "kaupustella", "kausijuoppo", "kausijuoppous", "kausittain", "kautta", "kautta-ajo", "kauttaaltaan"
, "kautta rantain", "kavahtaa", "kavalasti", "kavaltaa", "kaveerata", "kaventaa", "kaventua", "kaveta", "kavuta", "kehaista", "kehdata", "kehitellä", "kehitteille", "kehitteillä", "kehittyä", "kehittää", "kehitysvammainen", "kehitysvammaisuus", "kehityttää", "kehiä"
, "kehjetä", "kehnontaa", "kehnontua", "kehnosti", "kehnota", "kehnätä", "kehotella", "kehottaa", "kehruuttaa", "kehrätä", "kehräyttää", "kehtokuolema", "kehua", "kehuskella", "kehuttavasti", "kehystää", "kehäkuolema", "kehäraakki"
, "keimit", "keino-", "keinotekoisesti"
, "keisarinistuin", "keisarinkruunu", "keittiönpöytä"
, "kellan-", "kellelleen", "kellellään", "kellojensoitto", "kellonlyömä", "kellonperät"
, "kellonvitjat", "kelteisilleen", "kelteisillään"
, "ken", "kengänkanta", "kengänkieli", "kengänkiilloke", "kengänkiillote", "kengänkiillottaja", "kengänkiillotus", "kengänkorjaus", "kengänkorko", "kengänkärki", "kengännauha", "kengännumero", "kengänpohja", "kengänpäällinen", "kengänvarsi", "kenkään", "kenollaan", "kenoon", "kenossa"
, "kentänvoimakkuus", "keralla", "keralle", "kerinpuut"
,"kerralla", "kerrallaan", "kerroksittain", "kerrottava"
, "kesemmäksi", "kesemmälle", "kesemmällä", "kesempänä", "keskelle", "keskellä", "keskeltä", "keskemmä", "keskemmäksi", "keskemmälle", "keskemmällä", "keskemmältä", "keskemmäs", "keskempänä", "keskempää"
, "keskenään", "keskessä", "keskestä", "keskeyksiin", "keskeyksissä", "keskeytyksiin", "keskeytyksissä", "keski-", "keskipaikkeilla", "keskipaikkeille", "keskipaikkeilta", "keskipakois-"
, "keskenmeno"
, "keskityis", "keskitysleiri", "keskivaiheilla", "keskivaiheille", "keskivaiheilta", "keskiviikkoisin"
, "keskuudessa", "keskuudesta", "keskuuteen", "kesti", "kestitä", "kesäisin"
, "kesäteloilla", "kesäteloillaan", "kesäteloille", "kesäteloilleen", "kesäteloilta", "kesäteloiltaan", "ketale", "ketkale"
, "ketku", "ketunmyrkky", "keuhkoinfarkti", "keuhkokasvain", "keuhkokuume", "keuhkopussintulehdus", "keuhkoputkentulehdus", "keuhkosairaus", "keuhkosyöpä", "keuhkotauti", "keuhkotuberkuloosi", "keuhkotulehdus", "keuhkoveritulppa", "keulemmaksi", "keulemmas", "keulempaa", "keulempana", "kevytkenkäinen"
, "kevytmielinen", "kevytmielisesti", "keväin", "keväisin", "keväämmäksi", "keväämmälle", "keväämmällä", "keväämmäs", "keväämpänä", "kidnapata", "kidnappaaja", "kidnappaus", "kiduttaa", "kiduttaja", "kidutus", "kidutuskammio"
, "kommari", "kompura", "kompus"
, "kondylooma", "koni", "konitohtori"
, "konkreettisesti", "konservatiivisesti"
, "konstikkaasti", "kontallaan", "kontalleen", "kontillaan", "kontilleen"
, "koolla", "koolle", "koomisesti", "koossa", "kopeasti", "koppavasti"
, "koreasti", "koreittain", "koris", "koristeellisesti"
, "korjaamattomasti", "korjussa", "korjuun", "korjuuseen", "korjuussa", "korkealla", "korkealle", "korkealta", "korkeasti", "korkeimmillaan", "korkeimmilleen", "korkeintaan", "korkenee"
, "korkeussuhteet", "koronaariskleroosi", "koronaaritauti", "koronaarivaltimo", "korosteisesti"
, "korrektisti", "korskeasti", "korsteeni", "kortonki"
, "koruttomasti", "korvantaus", "korvantausta", "korviahuumaava", "korviasärkevä", "korviavihlova", "korvilla", "korville", "korvis", "korvissa"
, "kidutuskeino", "kidutusväline", "kiehtovasti", "kielellisesti", "kielevästi"
, "kieliopillisesti", "kielteisesti", "kieltämättä", "kieppeille", "kieppeillä", "kieppeissä", "kierosti"
, "kierroksittain", "kierryksiin", "kierryksissä", "kierryksistä", "kierteisesti", "kiertoteitse"
, "kiharaan", "kiharassa", "kihloihin", "kihloissa", "kiihdyksiin", "kiihdyksissä", "kiihdyksissään"
, "kiihkeästi", "kiihkoisasti", "kiihkottomasti", "kiihottumisherkkyys", "kiihottumisvaihe", "kiihottuneisuus", "kiihotustila", "kiihtymystila", "kiihtyneisyys", "kiikissä", "kiikistä", "kiikkiin", "kiikun kaakun"
, "kiima-aika", "kiimainen", "kiinnemmäksi", "kiinnemmäs", "kiinnempänä", "kiinni", "kiinnostavasti"
, "kiinteästi", "kiintoisasti", "kiintyneisyys", "kiireellisesti", "kiireesti", "kiireettömästi", "kiireimmiten", "kiireisesti", "kiiruusti"
, "kiistattomasti", "kiistämättä", "kiistämättömästi", "kiitettävästi", "kiitti", "kiittimet", "kiittämättömästi", "kiivaasti", "kikkeli"
, "killillään", "kiloittain", "kilometreittäin", "kilpaa"
, "kilpasilla", "kilpasille", "kilsa", "kiltisti", "kiltsi", "kimakasti", "kimeästi", "kimma", "kimmoisasti"
, "kimppuun", "kimpsut", "kimpuittain", "kimpussa", "kimpusta", "kinkunpala", "kintereille", "kintereillä", "kintereiltä"
, "kippuraan", "kippurassa", "kireälle", "kireällä", "kireässä"
, "kiristyksissä"
, "kirjeitse"
, "kirkkopäivät", "kirkonmeno", "kirosana", "kirottu", "kirotusti", "kirous"
, "kirroosi", "kirroottinen"
, "kissanpäivät", "kissanristiäiset", "kissarutto", "kituset"
, "kiukuissaan", "kiukuspäissään", "kiusanpäiten", "kives", "kivespussi", "kivestulehdus", "kivipölykeuhko"
, "kivuliaasti", "klamydia", "klamydiatartunta", "klamydiatulehdus", "klitoris"
, "kobolttikanuuna", "kobolttipommi", "kodikkaasti", "koepala"
, "koeputkihedelmöitys", "koetteeksi", "koetteella", "koetteelle", "koetteilla", "koetteille", "kohden", "kohdunkaula", "kohdunlaskeuma", "kohdunnapukka", "kohdunpoisto", "kohdunrunko", "kohdunsisäinen", "kohdunsuu", "kohdunulkoinen", "kohdunvuokraus", "kohmeeseen", "kohmeessa"
, "koholla", "kohollaan", "koholle", "koholleen", "kohtaan", "kohtalaisesti", "kohtalokkaasti", "kohtapuoleen", "kohtapuoliin", "kohtapuolin", "kohtauksittain", "kohteliaasti", "kohti", "kohtisuorasti", "kohtsillään", "kohtsiltään", "kohtu", "kohtusyöpä", "kohtuuttomasti"
, "kokeeksi"
, "kokeellisesti", "kokemusperäisesti", "kokeneesti", "kokkarit", "kokoilta", "kokonaan", "kokonaiskustannukset", "kokonaismenot", "kokonaispisteet", "kokonaisvaltaisesti", "kokonaisyksikkökustannukset"
, "kokoon", "kokoperunat", "kokopäivätoiminen", "kokovartalopuudutus", "koleasti", "kolera", "kolerabakteeri"
, "kolibakteeri", "kolkosti", "kolkkaa", "kollektiivisesti", "kolmasti", "kolmestaan", "kolmesti", "kolmia"
, "kolminkertaisesti", "kolmisin", "kolmistaan", "kolmittain", "kolmiäänisesti", "kolmosraskaus"
, "komeasti"
, "kosketusmiina", "kosketustartunta", "kostomurha"
, "kotia", "kotieläintauti", "kotiin", "kotiinpäin", "kotiloma"
, "kotiryssä", "kotisynnytys", "kotoa"
, "kotona", "koukkuun", "koukussa"
, "kouluväkivalta", "kovaa", "kovaan", "kovalla", "kovalle", "kovassa"
, "kovilla", "koville", "kreikan kieli", "krematoida", "krematointi", "krematorio"
, "kriminaalipotilas"
, "kroonikko", "krooninen", "kroonisesti", "kroonistaa", "kroonistua", "kroonisuus", "kruununkalleudet", "kudoksensiirto", "kudosvaurio"
, "kuhun", "kuhunka", "kuivaa"
, "kuiviin", "kuivilla", "kuiville", "kuiviltaan"
, "kukkurallaan", "kukkuralleen", "kukkuranaan", "kukkuroillaan", "kukkuroilleen", "kulauksittain"
, "kuljetuskustannukset", "kulkeilla", "kulkeille", "kulkusalla", "kulkusalle"
, "kulli", "kulmatusten", "kulmittain", "kulttuurikilpailut"
, "kulutusmenot", "kulussa", "kumaraan", "kumarassa", "kumarruksiin", "kumarruksissa"
, "kummarit", "kummastuksissaan", "kummissaan", "kumollaan", "kumolleen", "kumoon", "kumossa"
, "kuninkuusravit"
, "kunnittain", "kunnossa"
, "kuntoon", "kuohuksiin", "kuohuksissa", "kuolaimet", "kuolema", "kuolemaantuomittu", "kuolemanhiljaisuus", "kuolemanhätä", "kuolemanjälkeinen", "kuolemankaarre", "kuolemankaipuu", "kuolemankauppa", "kuolemankauppias", "kuolemankello", "kuolemankolari", "kuolemankurva", "kuolemanleiri", "kuolemanloukku"
, "kuolemanmerkki", "kuolemanpartio", "kuolemanpelko", "kuolemanrangaistus", "kuolemansairas", "kuolemansynti", "kuolemansyy", "kuolemansäde", "kuolemantanssi", "kuolemantapaus", "kuolemantauti", "kuolemantuomio", "kuolemantuottamus", "kuolemantuska", "kuolemanvaara", "kuolemanvakava", "kuolemanvakavasti", "kuolemanvakavuus", "kuolemanväsynyt", "kuolematon", "kuolemattomuus", "kuolettava", "kuolettavasti", "kuolettavuus", "kuolevainen", "kuolevaisuus", "kuolevuus", "kuoliaaksi", "kuoliaana", "kuolinaika", "kuolinapu", "kuolinhetki", "kuolinilmoitus", "kuolinisku", "kuolinkamppailu", "kuolinkellot", "kuolinkouristus", "kuolinnaamio", "kuolinpesä", "kuolinpuku", "kuolinpäivä", "kuolinsanoma", "kuolinsyy", "kuolintodistus", "kuolinvuode", "kuolio", "kuolioinen", "kuolioitua", "kuolla", "kuolleenkoura", "kuolleeton", "kuolleisuus", "kuolleisuustilasto", "kuollut", "kuolo", "kuolokohta", "kuolonenkeli", "kuolonkalpea", "kuolonkalpeus", "kuolonkankeus", "kuolonkolari", "kuolonuhri"
, "kuorima-", "kuorimis-", "kuormittain", "kuparimyrkytys"
, "kupeella", "kupeelle", "kupeelta", "kupeeseen", "kupeessa", "kupeesta", "kuppa", "kuppainen", "kuppapahkura", "kuppatauti", "kuppatautinen"
, "kurillaan", "kurin", "kurista", "kurkkukipu", "kurkkumätä", "kurkkumätärokote", "kurkkumätärokotus", "kurkkutauti", "kurkkutulehdus"
, "kusaista", "kuseksia", "kuseskella", "kusettaa", "kusettaja", "kusi", "kusiainen", "kusiaispesä", "kusihätä", "kusiluistin", "kusinen", "kusiputka", "kusipäinen", "kusipää", "kusta"
, "kuteet", "kuteilla", "kuteille", "kutri", "kutrit"
, "kuukautinen", "kuukautishäiriö", "kuukautiskierto", "kuukautiskipu", "kuukautissuoja", "kuukautisveri", "kuukautisvuoto", "kuulemiin", "kuuliaiset"
, "kuulonheikkenemä", "kuulovamma", "kuulovammainen", "kuulovammaisuus", "kuulovika", "kuulumattomiin", "kuulumattomissa", "kuulumiset", "kuuluviin", "kuuluvilla", "kuuluville", "kuuluvilta", "kuuluvissa", "kuuluvista"
, "kuumehoure", "kuumekohtaus", "kuumekouristus", "kuumelääke", "kuumepotilas", "kuumereuma", "kuumesairas", "kuumesairaus", "kuumetauti", "kuumetautinen", "kuumiltaan", "kuumissaan", "kuunaan", "kuuromykkyys", "kuuromykkä", "kuuroittain", "kuurosokea"
, "kuurupiilosilla", "kuutioittain", "kuutiometreittäin"
, "kuutisen", "kuutisenkymmentä", "kuvaamataidonopettaja", "kuvaamattomasti", "kuvaannollisesti", "kuvallisesti", "kuvas"
, "kvalitatiivisesti", "kvantitatiivisesti"
, "kyhmyruusu", "kyljekkäin", "kyljelleen", "kyljellään", "kyljes", "kyljittäin", "kyljitysten", "kylkiluunmurtuma", "kylkimyyryä", "kylmilleen", "kylmillään", "kylmiltään", "kylmissään"
, "kylmäkiskoisesti", "kylmänvihat", "kylmäpäisesti", "kylmäsydämisesti", "kylmästi", "kylmäverisesti"
, "kylässä", "kylästä", "kylään", "kymmenen", "kymmenesti", "kymmenisen", "kymmenittäin"
, "kynsisieni", "kynsisilsa", "kypsi", "kypsästi"
, "kyrmyssä", "kyrmyyn", "kyrpiintyä", "kyrpä", "kyrvähtää", "kyrväyttää", "kysta", "kysyvästi", "kyykkysilleen", "kyykkysillään", "kyykkysiltään", "kyykkyyn"
, "kyykylleen", "kyykyllään", "kyykyltään", "kyykyssä", "kyykystä", "kyynisesti", "kyyrylleen", "kyyryllään", "kyyryltään", "kyyryssä", "kyyrystä", "kyyryyn", "kyytiä", "käden käänteessä"
, "käheästi", "kännipäissä", "kännipäissään"
, "kärjekkäästi", "kärkevästi", "kärkkäästi"
, "käsikaulaa", "käsikopelolla", "käsikopelolta", "käsiksi"
, "käsille", "käsillä", "käsin", "käsipohjaa", "käsissä", "käsityksin", "käsitysten"
, "kätkytkuolema"
, "käymäjalkaa", "käymäseltä", "käymäseltään"
, "käyvästi"
, "käärinliina", "käärmeissään"
, "köniin", "köykkyyn", "köykyssä", "köykystä", "köyryssä", "köyrystä", "köyryyn"
, "laajalti"
, "laatuunkäyvästi"
, "lahdata", "laidemmaksi", "laidemmalla", "laidemmalle", "laidemmalta", "laidemmas"
, "laidunhalvaus", "laidunkouristus", "laidunkuume", "laidempaa", "laidempana", "laikkutauti"
, "laita-alkoholisti"
, "laitamyötäinen", "laitoshoito", "laitospotilas"
, "lakastumistauti", "lakiaukile"
, "laktaasinpuutos", "laktoosi-intoleranssi", "laktoosi-intolerantti", "lamaan", "lamassa", "lamasta"
, "lankeemus"
, "lannepisto", "laossa", "laparoskopia", "laparoskopialeikkaus", "lapamato"
, "lappeellaan", "lappeelleen", "lapsenpäästö", "lapsenryöstö", "lapsettomuus", "lapsihalvaus", "lapsikauppa", "lapsikuolleisuus", "lapsiporno", "lapsipornografia", "lapsipotilas", "lapsiprostituoitu", "lapsiprostituutio"
, "lapsirikollinen", "lapsiseksimatkailu", "lapsivesitutkimus", "lapsivuodekuume", "lasaretti", "laserhoito", "laserleikkaus", "lasiainen", "lasiaisneste"
, "laskeuma", "laskeutuma", "laskimonlaajentuma", "laskimotukos", "laskimotulehdus"
, "lastasidos"
, "latenssivaihe", "lattiasieni", "lauantaisin"
, "laukkuryssä", "laumoittain"
, "lavantauti", "lavantautibakteeri", "lavantautiepidemia", "lavantautipotilas", "lavantautirokotus", "lavantautitartunta"
, "legioonalaistauti", "lehtikuolema"
, "lehtilapsi", "leikillään"
, "leikisti", "leikiten", "leikkausarpi", "leikkaushaava", "leikkaushoito", "leikkausjono", "leikkauspotilas", "leikkauspöytä", "leikkaussali", "leikkausveitsi", "leikkausviilto"
, "lemmentuska"
, "lennokkaasti", "lentomyrkytys"
, "lento-onnettomuus", "lentopostitse", "lentoturma", "leppeästi", "leppoisasti", "leppymättömästi"
, "lepra", "lepsusti", "lerpalla", "lerpallaan", "lerpalle", "lerpalleen", "lerppua", "lesbopari", "leskeys", "leski", "leskikuningatar", "leskimies", "leskirouva", "leskiäiti", "letkeästi", "leudosti"
, "leuhkasti", "leukavasti", "leukemia", "leveälti", "leveästi", "levollisesti", "levottomasti"
, "levälleen", "levällään", "leväperäisesti", "liberaalisesti", "liberaalisti", "liehakkaasti"
, "liepeille", "liepeillä", "liepeiltä", "liettua", "liettuan kieli", "lievästi"
, "lihasheikkous", "lihaskasvain", "lihaskipu", "lihaskouristus", "lihaskramppi", "lihasrappeuma", "lihasreuma", "lihasrevähtymä", "lihassurkastuma", "lihassärky", "lihasvamma", "lihasvenähtymä", "liiaksi", "liialti", "liian", "liiemmin", "liiemmälti"
, "liikaa", "liika-annostus", "liikahappoisuus", "liikaherkkyys", "liikaherkkä", "liikajännitys", "liikakansoittua", "liikakansoitus", "liikakasvu", "liikakuormitus", "liikalihava", "liikalihavuus", "liikarasittunut", "liikarasitus", "liikatoiminta", "liikekannalla", "liikekannalle", "liikennejuopumus", "liikennekaaos", "liikennekuolema"
, "liikenneonnettomuus", "liikennepako", "liikennerikkomus", "liikennerikos", "liikenneturma", "liikennevahinko", "liiketaloudellisesti", "liiketappio", "liikkeelle", "liikkeellä", "liikkeessä"
, "liikkumisvaikeus", "liikkuvasti", "liikuntaesteinen", "liikuntakyvytön", "liikuntarajoitteinen", "liikuntavamma", "liikuntavammainen", "liikuttavasti", "liimakorva", "liioin", "liiskaksi", "liiskana"
, "liittoutuneet", "liivin kieli", "likavaatteet"
, "likelle", "likellä", "likeltä", "likemmäksi", "likemmäs", "likempänä", "likempää", "likimmäksi", "likimmäs", "likimpänä", "likimpää", "likoon", "likvori"
, "linnanrauniot", "linnoitusjoukot"
, "linnuntietä", "lintallaan", "lintalleen", "lintassa", "lintukotolaiset", "lintuniisikangas", "lintuniisisidos", "liossa", "liosta", "liperit", "lipettiin", "lipeämyrkytys"
, "lirunlaru"
, "lisäksi", "lisäkulut", "litistyksiin", "litistyksissä", "litroittain"
, "liuotushoito", "livohkaan"
, "loissairaus", "loistartunta", "loistauti", "loitolla", "loitolle", "loitolta", "loitommaksi", "loitommas", "loitompaa", "loitompana"
, "lomaan", "lomakkain", "lolita"
, "herätemiina"
, "lomassa", "lomasta", "lommoilla", "loogisesti", "loppumattomasti"
, "loppuun", "lopuillaan", "lopuksi", "lopulla", "lopullaan", "lopullisesti", "lopulta", "lopussa", "loputtomasti", "loputtomiin", "lossiksi"
, "lues"
, "luihusti", "luimussa", "luimuun", "lujaa", "lujaan", "lujakätisesti", "lujalla", "lujalle", "lujassa", "lujasta", "lujasti", "lujilla", "lujille", "lukien"
, "lukkoon", "lukossa", "lukosta", "lukuisasti", "lukumääräisesti"
, "lukuun ottamatta", "lumbaalipunktio", "lumisotasilla"
, "lunkisti", "luo", "luokkasota", "luokkaviha"
, "luokse", "luona", "luonnehäiriö", "luonnehäiriöinen", "luonnenäytelmä", "luonnevikainen", "luonnikkaasti", "luonnollisesti"
, "luonnonmukaisesti", "luonnonolot", "luonnostaan", "luonnottomasti", "luontaisesti", "luonteenomaisesti"
, "luontevasti", "luontojaan", "luota", "luotaantyöntävästi", "luotettavasti", "luottamuksellisesti"
, "luotti", "lurpalla", "lurpallaan", "lurpalle", "lurpalleen", "lurpassa", "lurppaan", "lutka"
, "lutkuttaa", "lutkutus", "luukasvain", "luukato", "luumätä", "luunmurtuma", "luunsiirto", "luunsiirtoleikkaus", "luusyöpä", "luuytimensiirto"
, "lyhyeen", "lyhyelle", "lyhyellä", "lyhytkirurgia", "lyijymyrkytys"
, "lymfooma", "lysyssä", "lysyyn", "lyttyyn", "lytyssä"
, "lähelle", "lähellä", "läheltä", "lähemmin", "lähemmä", "lähemmäksi", "lähemmäs", "lähempi", "lähempänä", "lähempää", "lähentely", "lähettyville", "lähettyvillä", "lähettyviltä", "lähetyssaarnaaja-asento"
, "lähimailla", "lähimaille", "lähimailta", "lähimmin", "lähimmäksi", "lähimmäs", "lähimpänä", "lähimpää", "lähin", "lähiseutuvilla", "lähiseutuville", "lähiseutuvilta", "lähtiäiset", "lähtökuopat"
, "lähtöpassit", "läjäpäissä", "läksiäiset", "läksiäisjuhla", "läksiäiskahvit", "läksiäispuhe", "läkähdyksiin", "läkähdyksissä", "läkähdyksissään"
, "lämpimikseen", "lämpimiltään", "lämpimältään", "lämpöhalvaus"
, "lämpöydinpommi", "länget", "lännemmäksi", "lännemmäs", "lännempänä", "lännempää", "länsipuolitse", "länttään", "läntälleen", "läntällään", "läntässä", "läpeensä"
, "läppävika", "läppävikainen", "läskimaha", "läskimooses"
, "lääkeaddikti", "lääkeainemyrkytys", "lääkeriippuvuus", "lääkärinapu", "lääkärinhoito", "lääkärinlausunto", "lääkärinpalkkio", "lääkärintarkastus", "lääkärintodistus", "lääkärintutkimus", "lääkärinvirka"
, "lääneittäin", "lääpälleen", "lääpällään", "löyhdyttää", "löyhennys", "löyhentyä", "löyhentää", "löyhetä", "löyhkä", "löyhkätä", "löyhtyä", "löyhytellä", "löyhyttää", "löyhyys", "löyhä", "löyhähtää", "löyhäkätinen", "löyhäpäinen", "löyhärakenteinen", "löyhästi", "löyhäsuinen", "löyly", "löylyhuone", "löylykauha", "löylymies", "löylynlyömä", "löylyttää", "löylytys", "löylyvesi", "löysentyä", "löysentää", "löystyttää", "löystyä", "löysyys", "löysä", "löysäpäinen", "löysästi", "löysätä", "löytymättömiin", "löytymättömissä", "löytäjä", "löytää", "löytö", "löytölapsi", "löytöpaikka"
, "maahanhyökkäys", "maahanpaniaiset", "maahansyöksy", "maahantunkeutuja", "maahantunkeutuminen", "maailmanloppu"
, "maailmanpalo", "maailmansota", "maailmantuska", "maailmanvallankumous"
, "maalaisesti", "maalaisittain", "maalaismainesti", "maalauksellisesti"
, "maaltapako", "maamuna", "maanantaisin", "maanikko", "maaninen", "maanis-depressiivinen", "maanjäristys", "maanjäristysaalto", "maanjäristysmittari", "maanjäristysoppi", "maankavallus", "maankavaltaja", "maanpako", "maanpakolainen", "maanpakolaisuus", "maanpetoksellinen", "maanpetos", "maanpetturi"
, "maanrako", "maansuru", "maanteitse", "maantiegangsteri", "maantienoja", "maantierosvo", "maantieteellinen", "maantieteellisesti", "maanvaiva", "maanvajoama", "maanvieremä", "maanvyörymä", "maanääri", "maaorja", "maaorjuus"
, "maarin", "maasodankäynti", "maasota", "maasotatoimi", "maastakarkotus", "maastoitse", "maastopalo"
, "maatameno", "maatapano", "maate", "maateitse", "maaton", "machiavellilainen", "machiavellismi", "machiavellisti", "machiavellistinen", "madonhäätö", "madonkantaja", "madonluku", "madonsyömä", "magna cum laude approbatur"
, "magneettimiina", "magneettisesti", "mahahaava", "mahahuuhtelu", "mahakatarri", "mahakipu", "mahalasku", "mahanpuru", "mahasyöpä", "mahatauti", "mahavaiva", "mahdikkaasti", "mahdollisesti", "mahdottomasti", "mahtailevasti"
, "maihin"
, "maissa", "maista", "maitokuume"
, "maitorauhastulehdus", "maitorupi", "maitse", "maittain", "make-up"
, "makki", "makkilanta", "maksakirroosi", "maksasairaus", "maksasyöpä", "maksatulehudus"
, "makuulla", "makuulle", "makuulta", "makuuhaava", "malaria", "malariasääski", "maligni", "malignisoitua", "malignistua", "maligniteetti", "malignoitua"
, "maltaat", "mammografia"
, "mammuttitauti", "management", "manne"
, "manöveroida", "manöverointi", "manövroida", "marihuana"
, "marjapussi", "markkinat", "marmelaati"
, "marssimurtuma", "marttyyrikuolema", "masennus", "masennuskausi", "masennuslääke", "masennustila", "massamurha", "massapsykoosi"
, "masturbaatio", "masturboida", "masturbointi", "matalalla", "matalalle", "matalalta"
, "matkalla", "matkalle"
, "matsi", "matsku"
, "medisiina", "medisiinari"
, "meikku", "meitski", "meitsi", "melanooma"
, "menehdyksiin", "menehdyksissä", "menehdyksissään", "meneillä", "meneillään", "menkat", "menkut", "mennessä"
, "menopaussi", "menopäällä", "mensikset", "menstruaatio", "menstruoida", "mensut"
, "merikipeä", "merisairas", "meriteitse", "meritse"
, "merkille pantava"
, "mesta", "mesu", "metadoni"
, "metastaasi", "metastaattinen", "metastasoida", "metastasointi", "metelivesi", "metreittäin"
, "metsäkuolema"
, "miehelässä", "miehelään", "miehenkipeä"
, "miehennielijä", "mieleen", "mielellään", "mielestä"
, "mielihyvin", "mielikseen", "mieliksi", "mielin kielin", "mielin määrin", "mielissään", "mieluimmin", "mieluiten", "mieluummin", "mieluusti"
, "miesmuistiin", "miesmurha", "miestennielijä", "mihin", "mihinkin", "mihinkä", "mihinkään"
, "mihinpäin", "mikin", "miksi", "mikä", "mikäkin", "mikäli", "mikään"
, "miljoonittain", "millainen", "milloin", "milloinka", "milloinkaan", "milloinkin", "millänsäkään", "millään", "milläänkään", "miltei", "mimmoinen"
, "minne", "minnekin", "minnekä", "minnekään", "minnepäin", "minunlaiseni", "minuuteittain", "minä", "missä"
, "missäkin", "missäpäin", "missään", "mistä", "mistäkin", "mistäpäin", "mistään", "misu", "miten", "mitenkin", "mitenkuten", "mitenkä", "mitenkään", "miten päin", "mittain", "mitä"
, "moikaa"
, "mongoli", "mongolidi", "mongolidinen", "mongolismi", "mongoloidi"
, "monimielinen", "monimielisesti", "monimielisyys", "monioireinen", "moniongelmainen"
, "monisynnyttäjä", "monivammainen", "monottaa", "monstrumi"
, "morfiini", "morfinismi", "morfinisti"
, "morkkis", "mortaliteetti", "muassa"
, "muiluttaa", "muiluttaja", "muilutus", "muistinmenetys"
, "muistokirjoitus", "muistolehto", "muistopuhe", "muistotilaisuus", "mukaa", "mukaan luettuna", "mukaan lukien", "mukkelis makkelis"
, "mulatti", "mulkku", "mullin mallin", "multippeliskleroosi", "muna", "munanjohdin", "munarakkula", "munasarja", "munasarjasyöpä", "munasolu", "munata"
, "munatorvi", "munuainen", "munuaisallas", "munuaisensiirto", "munuaiskeränen", "munuaiskivi", "munuaiskivitauti", "munuaiskoje", "munuaistauti", "munuaistulehdus", "muodosteilla"
, "muotokuvanpaljastus", "muotokuvanpaljastustilaisuus"
, "murha", "murhaaja", "murha-ase", "murhaava", "murhaavasti", "murhajuttu", "murhamies", "murhanhimo", "murhanhimoinen", "murhapaikka", "murhapolttaja", "murhapoltto", "murhata", "murhauttaa", "murhayritys", "murheissaan", "murhemielelle", "murhemielellä"
, "murskaksi", "murskana"
, "musiikkiopinnot", "mustalainen", "mustalaiselämä", "mustalaiskieli", "mustalaiskulttuuri", "mustalaisleiri", "mustalaismies", "mustalaismusiikki", "mustalaisnainen", "mustalaisorkesteri", "mustalaispriimas", "mustalaispuku"
, "mustaleski", "mustamies", "mustankipeys", "mustankipeä", "mustasukkainen", "mustasukkaisesti", "mustasukkaisuus", "mustasukkaisuusharha", "mustenee", "mutakuono"
, "mutrulla", "mutrullaan", "mutrulle", "mutrulleen", "mutrussa", "mutruun", "muualla", "muualle", "muualta", "muuanne", "muukalaispelko", "muukalaisviha", "muulloin", "muumiotauti", "muun muassa"
, "muutoin", "mynkään", "myooma"
, "myrkkystruuma", "myrkytyskuolema", "myrkytysmurha"
, "myyräkuume", "myöhemmin", "myöhemmäksi", "myöhemmäs", "myöhempään", "myöhäiseen", "myöhäisintään", "myöhälle", "myöhällä", "myöhässä", "myöhään"
, "myös", "myöskin", "myöskään", "myöten", "myötä", "myötäkarvaan", "myötäpäivään", "myötäsukaan", "myötäänsä", "mä"
, "mälli", "männynversosyöpä", "mäntti", "mänttipää", "mäsis", "mäskäksi"
, "mäskänä", "mätimuna", "mätämuna", "mätänemiskaasu", "mätänemisprosessi", "mätänemistila", "mätäpaise", "määrä-"
, "möhömaha", "möhömahainen", "mömmö", "mönkään", "naamahermohalvaus"
, "naara", "naaraspontti", "naatti", "nahkamuna", "nahkan-"
, "nahkapää", "naida", "naikkonen", "naimisiin", "naimisissa", "nainti"
, "naistentauti", "naistentautilääkäri", "naistentautiopillinen", "naistentautioppi", "naku", "nakupelle", "nakuranta", "nalkissa", "nalkkiin", "nakutyttö"
, "namusetä", "nano-", "napatyrä"
, "narkata", "narkkari", "narkkaus", "narkkis", "narkomaani", "narkomania", "narttu", "natsi", "natsilainen"
, "natsismi", "natsitervehdys", "naturismi", "naturisti", "naurusuin"
, "ne", "neekeri", "neekeriorja", "neekeriorjuus", "nekrologi", "nekroosi", "nekroottinen", "nekrotisoitua", "nekru", "neli-", "nelinkertaisesti"
,"känni"
, "neitseellinen"
, "neitseellisesti"
, "neitseellisyys"
, "neitsyt"
, "neitsytkammio"
, "neitsytmatka"
, "neitsytpuhe"
, "neitsyys"
, "aunus"
, "au pair -tyttö"
, "neliraajahalvaus", "nelson"
, "nestehukka", "nestor"
, "neuralgia", "neuralginen", "neurasteenikko", "neurasteeninen", "neurastenia", "neuriitti", "neurokirurgi", "neurokirurgia", "neurolingvistiikka", "neurologi", "neurologia", "neurologinen", "neuroni", "neuroosi", "neurootikko", "neuroottinen", "neuroottistua", "neuroottisuus", "neurotisoitua", "neutronipommi"
, "neuvotteilla", "neuvottelupäivät", "neuvotteluteitse", "neuvottelutietä", "nidoksittain", "nielemisvaikeus", "nielurisatulehdus", "nielutulehdus", "niin ikään", "niinku", "niin kuin", "niin kutsuttu", "niin päin", "niin sanottu", "niin sanotusti"
, "nikkeliallergia", "nikkeliallergikko", "nikkelimyrkytys", "nikotiinimyrkytys", "nikotinisti", "nilelle", "nilellä", "nilkki"
, "nimiäiset", "nipin napin", "nippa nappa", "nipuittain"
, "nirpalla", "nirpallaan", "nirpassa", "nirri", "nisti", "niukin naukin"
, "niveljäykistymä", "nivelkipu", "nivelreuma", "nivelrikko", "nivelsairaus", "nivelsärky", "niveltauti", "niveltulehdus", "nivuset", "nivustyrä", "nojaan", "nojalla", "nojallaan", "nojalleen", "nojassa", "noin päin", "nokakkain", "nokatusten", "nokikkain", "nokittain", "nokitusten"
, "nokkosihottuma", "nokkoskuume", "nokkosrokko", "noloissaan"
, "normaaliolot", "norsutauti"
, "nudismi", "nudisti", "nudistileiri", "nudistiranta"
, "nukuksiin", "nukuksissa"
, "nuokuksiin", "nuokuksissa", "nuoremmakseen", "nuoremmuuttaan"
, "nureissaan", "nurkilla", "nurkille"
, "nussia", "nuuduksissa", "nykyiselleen", "nykyisellään", "nykyisin", "nykyjään", "nykyolot"
, "nymfetti", "nymfomaani", "nymfomaaninen", "nymfomania", "nyreissään", "nyrpeissään", "nyttemmin"
, "nähdäkseen", "nähtäviin", "nähtäville", "nähtävillä", "nähtävissä", "näkymättömiin", "näkymättömissä", "näkyviin", "näkyville", "näkyvillä", "näkyviltä", "näkyvissä", "näkyvistä"
, "näköjään", "näkösälle", "näkösällä", "näkösältä", "nälissään", "nälkäkuolema", "nänni", "nänninpiha"
, "närästää", "näytille", "näytillä", "näytteille", "näytteillä"
, "näännyksiin", "näännyksissä", "obduktio", "ohari"
, "oheen", "ohella", "ohessa", "ohesta", "ohitse", "ohitusleikkaus"
, "ohrapirtelö", "ohutneulabiopsia", "ohutneulanäyte", "oidipuskompleksi"
, "oidipaalinen"
, "oikeaan", "oikealla", "oikealle", "oikealta", "oikeassa"
, "oikeusteitse", "oikoisenaan", "oikopäätä", "oikoteitse"
, "ojolla", "ojollaan", "ojolle", "ojolleen", "ojoon", "ojossa", "oksasakset"
, "olakkain", "olevinaan", "oltavat"
, "oluthumala"
, "olutjuoppo"
, "olutkapakka"
, "omenalohko", "omenanlohko", "omenanviipale", "omenavarkaisiin", "omenavarkaissa", "omenavarkaista", "omenaviipale", "omia", "omiaan", "omiansa", "omillaan", "omilleen"
, "onania", "onanoida"
, "onnellisuuspilleri", "onteloammus", "ontelosyylä", "onttolaskimo", "oopiumi", "oopiumihumala", "oopiumiluola", "oopiuminpolttaja", "oopiumipiippu", "oopiumiunikko"
, "open house", "open house -kutsut", "Opetushallitus"
, "opiaatti", "opillisesti", "oppineesti"
, "optimistisesti", "optisesti", "oraakkelimaisesti", "ordoviikki", "ordoviikkikausi", "ordoviikkinen"
, "orgaanisesti", "orgasmi", "orgastinen", "orgiat", "orientalisti", "orientalistiikka", "orientti", "orjallisesti", "orjamaisesti", "orkku"
, "osaaottavasti", "osakseen", "osaksi", "osapäivätoimisesti", "osin"
, "osittain", "oskarinkokoinen", "ossi", "osso buco", "ostari", "osteomalasia", "osteoporoosi", "ostjakki"
, "osuvasti", "otaksuttavasti", "otollisesti", "oudokseltaan", "oudosti", "out", "output", "outsider", "ouzo", "ovaario", "ovariaalinen", "ovelasti"
, "paatoksellisesti"
, "paavalinkukka", "pahanilkisesti", "pahankurisesti", "pahanlaatuinen", "pahanlaatuistua", "pahanlaatuisuus", "pahanlaisesti", "pahanpäiväisesti", "pahansuovasti", "pahantuulisesti", "pahasti", "paheellisesti", "pahemmin", "pahimmillaan", "pahimmilleen", "pahimmin", "pahimmoiksi", "pahimmoillaan", "pahimmoilleen", "pahiten", "pahitteeksi", "pahkaa"
, "pahki", "pahoillaan", "pahoilleen", "pahoin", "pahoinpidellä", "pahoinpitelijä", "pahoinpitely", "pahuksesti", "paikalla", "paikallaan", "paikalle", "paikalleen", "paikallisesti", "paikalta", "paikaltaan"
, "paikkakunnittain", "paikka paikoin", "paikkeilla", "paikkeille", "paikkeilta", "paikoillaan", "paikoilleen", "paikoiltaan", "paikoin", "paikoitellen", "paikoittain", "painavasti"
, "paineenalainen", "painokkaasti"
, "painuksiin", "painuksissa", "painuksista", "paisuksiin", "paisuksissa", "paitahihasillaan", "paitahihasilleen", "paitasillaan", "paitasilleen", "paitis", "paitsi", "paituli"
, "pakahduksiin", "pakahduksissa", "pakahduksissaan", "pakanasti", "pakeilla", "pakeillaan", "pakeille", "pakeilleen", "pakeilta", "pakeiltaan", "pakettipommi"
, "pakkoavioliitto", "pakkohoito", "pakkolasku", "pakkoloma", "pakkolomauttaa", "pakkolomautus", "pakkomielle", "pakkoneuroosi", "pakkoneurootikko", "pakkoneuroottinen", "pakkopaita", "pakkoruokinta", "pakkoteitse", "pakkotyöleiri", "pakkotyövanki", "pakoon"
, "pakosalla", "pakosalle", "pakostakin", "pakottomasti", "paksulti", "paksusti", "palavissaan", "palelluksissa", "palelluksissaan", "paleltumisvamma", "paljaaltaan"
, "paljasjaloin", "paljolta", "paljolti", "paljon", "palkattomasti", "palkkamurhaaja", "palkkasoturi"
, "palliatiivinen", "pallinaama", "pallosilla", "pallosille", "palohaava"
, "paloittain", "palopommi", "palorakkula", "palovamma", "paloviina", "palpaatio", "palpoida", "palpointi", "palstoittain"
, "palvelijanhuone", "palvelukseenastumismääräys", "palvontamenot", "pamahdella", "pamahdus", "pamahtaa", "pamaus", "pamautella", "pamauttaa", "pamppu", "pamputtaa", "pamputus", "panama", "panamahattu", "panamasidos"
, "panetella", "panettaa", "panettelija", "panettelu", "paniikkihäiriö", "paniikkikohtaus", "pankkirosvo", "pankkiryöstäjä", "pankkiryöstö", "panna", "pannajulistus", "pano", "panos", "panostaa", "panostaja", "panostus", "panssari", "panssariammus", "panssariase", "panssariauto", "panssarijoukot", "panssarijuna", "panssarikauhu", "panssarikranaatti"
, "panssarilaiva", "panssarilasi", "panssariliivi", "panssariluoti", "panssarimiina", "panssarintorjunta", "panssarintorjunta-ase", "panssarintorjuntajoukkue", "panssarintorjuntakomppania", "panssarintorjuntaohjus", "panssarintorjuntatykki", "panssariovi", "panssarivaunu", "panttivankeus", "panttivanki", "paossa", "Papa-koe", "Papa-näyte"
, "paperisota", "papintappaja", "papillooma", "papilloomavirus", "parabellum"
, "parahdus", "parahtaa", "parakki", "parakkikylä", "parannuksentekijä", "parannussaarna", "paranoia", "paranoidi", "paranoidinen", "paranooikko", "paranooinen", "parantumaton", "parantumattomasti", "parantumattomuus", "parasiitti", "par avion", "parfait"
, "pariisinperunat", "pariisitar", "parintuho", "parisuhdeväkivalta", "paritella", "parittaa", "parittaja", "paritteluelin", "paritus", "parjaaja", "parjata", "parjaus", "parka", "parkaista", "parkaisu", "Parkinsonin tauti", "parkinsonismi", "parkkisakko"
, "parku", "parkua", "parkuna", "parlamenttivaalit", "partaalla", "partaalle", "partajeesus", "partaterä", "partaveitsi", "partisaani"
, "party", "parvorokko", "parvovirus", "pascal", "paska", "paskainen", "paskamainen", "paskantaa", "paskantärkeä", "paskapuhe", "paskapää", "paskiainen", "passepartout", "passipoliisi", "passittaa", "passitus"
, "pataljoona", "pataluhaksi", "Patenttihallitus", "patogeeninen", "patologi", "patologia", "patologinen", "patteristi", "patteristo"
, "paukahdella", "paukahdus", "paukahtaa", "paukapää", "paukaus", "paukautella", "paukauttaa", "pauke", "paukkaa", "paukku", "paukkua", "paukkupanos", "paukkupatruuna", "paukkupommi", "paukutella", "paukuttaa", "paukuttelu", "paukutus", "pederasti", "pederastia", "pederastinen", "pediatri", "pediatria", "pedofiili", "pedofiilinen", "pedofilia", "peeaa", "peeveli", "peevelinmoinen", "peevelisti", "peffa", "peffamäki"
, "pehva", "peijakas", "peijakkaanmoinen", "peijakkaasti", "peijooni", "peitejärjestö", "peitossa", "peitosta", "peittä", "peitta-aine", "peittaustoiminta", "pekka"
, "pelastusarmeijalainen", "pelihelvetti", "pelihimo", "peliluola", "pelinarkomaani", "peliongelmainen", "pelivelka"
, "pellinnaru", "pellinnuora", "peltoetana"
, "pemppu", "penetraatio", "penetroida", "penikka", "penikkatauti", "penis", "penisilliini", "penisilliinihoito", "penisilliinikuuri", "penisilliiniruiske", "peniskateus", "pennalismi"
, "pentele", "penteleesti", "peppu", "per", "performaatio", "perhana", "perhananmoinen", "perhanasti", "perhehelvetti"
, "perhetragedia", "perheväkivalta", "perhospihvi"
, "perimyssota", "perivihollinen", "perjantaipullo", "perkele", "perkeleellinen", "perkeleenmoinen", "perkeleesti", "perkule"
, "pernarutto", "pernisioosi", "pernisioosinen", "pernisiöösi", "persaukinen", "persaukset", "perse", "perseennuolija", "perskat", "perskänni", "persläpi", "persnetto", "persukset", "persuukset"
, "perunantaimi", "perunarutto", "perunasyöpä"
, "perussairaus", "perustauti", "perversio", "perversiteetti", "perverssi", "perverssiys", "pervo", "peräaukko"
];

const forbiddenSet = new Set(forbiddenWords.filter(Boolean).map(w => w.toLowerCase()));

//seuraava alaken 53000
let allWords = [];
let commonWords = [];
let usedWordsInThisGame = [];

const parseWords = (text, maxLines = Infinity) => {
    const seen = new Set();
    
    // 1. Разбиваем файл строго по переносам строк
    let lines = text.split('\n');
    
    // 2. Оставляем только строки с 1 по 36999 (индексы от 0 до 36998)
    if (maxLines !== Infinity) {
        lines = lines.slice(0, maxLines - 1); 
    }

    // 3. Соединяем обратно и обрабатываем каждую строку по вашему алгоритму
    return lines
        .join('\n')
        .split(/[,\n]/)
        .map(w => w.trim())
        .filter(w => w.length >= 3)
        .map(w => ({ original: w, normalized: w.toLowerCase() }))
        .filter(item => !forbiddenSet.has(item.normalized))
        .filter(item => {
            if (seen.has(item.normalized)) return false;
            seen.add(item.normalized);
            return true;
        })
        .map(item => item.original); // Возвращает слова в нижнем регистре
};

let rareWordsSet = new Set();

// Päivitetyt fetch-kutsut:
fetch('words/kaikkisanat.txt')
    .then(res => res.text())
    .then(d => {
        allWords = parseWords(d, 53000);
        // Luodaan valmis indeksi isoilla kirjaimilla salamannopeaa hakua varten
        rareWordsSet = new Set(allWords.map(w => capitalize(w)));
    })
    .catch(e => console.log("kaikkisanat.txt failed:", e));

fetch('words/yleisetsanat.txt')
    .then(res => res.text())
    .then(d => {
        commonWords = parseWords(d);
    })
    .catch(e => console.log("yleisetsanat.txt failed:", e));
